export const GithubLink = "https://github.com/Syxtyz"
export const FacebookLink = "https://www.facebook.com/Tweiqht"
export const InstagramLink = "https://www.instagram.com/sejii8/"
export const LinkedinLink = "https://www.linkedin.com/in/tweiqht/"
export const calLink = "https://cal.com/tweiqht"